### ISSUE TITLE
plone.restapi 8.43.4 does not exist

### ISSUE THREAD

**Issue by erral** [starzel/buildout#69]
This version is linked from https://github.com/starzel/buildout/blob/master/linkto/hotfixes/5.2.10.cfg#L13-L14 but it doesn't exist.

**Comment by pbauer** [comment]
Correct, I mentioned that in https://community.plone.org/t/plone-security-advisory-2023-09-21/17941/4

**Comment by pbauer** [comment]
Fixed, it was supposed to be 8.43.3
